import type { StockCategory } from '../types';

export const INITIAL_STOCK_DATA: StockCategory[] = [
  {
    label: 'Red Wines',
    items: [
      { name: 'House Cabernet', count: 0 },
      { name: 'House Chianti', count: 0 },
      { name: 'Sterling Cabernet', count: 0 },
      { name: 'Bonorli Super Tuscan', count: 0 },
      { name: 'Arché Montepulciano', count: 0 },
      { name: 'Amalaya Malbec', count: 0 },
      { name: 'Saddlebred Pinot Noir', count: 0 },
      { name: "Calea Nero d'Avola", count: 0 },
    ],
  },
  {
    label: 'White Wines',
    items: [
      { name: 'House Pinot Grigio', count: 0 },
      { name: 'Kato Sauv Blanc', count: 0 },
      { name: 'Sortesele Pinot Grigio', count: 0 },
      { name: 'Picco Del Sol Vermentino', count: 0 },
      { name: 'Santi Rosé', count: 0 },
      { name: 'Riesling', count: 0 },
      { name: 'Sauvignon Blanc', count: 0 },
      { name: 'Lamberti Prosecco', count: 0 },
      { name: 'Franciscan Chardonnnay', count: 0 },
      { name: 'Bramito Chardonnnay', count: 0 },
      { name: 'Zebo Moscato', count: 0 },
    ],
  },
  {
    label: 'Beers, Teas, Splits and Sodas',
    items: [
      { name: 'Brilla Rosé', count: 0 },
      { name: 'Surfside', count: 0 },
      { name: 'Peroni 0.0', count: 0 },
      { name: 'Brilla Blue', count: 0 },
      { name: 'Corona', count: 0 },
      { name: 'Coors Light', count: 0 },
      { name: 'Nine Pin Cider', count: 0 },
      { name: 'Saranac Root Beer', count: 0 },
      { name: 'Saranac Sherley Temple', count: 0 },
    ],
  },
  {
    label: '400 Speedwell',
    items: [
      { name: 'House Vodka', count: 0 },
      { name: 'Kahlua', count: 0 },
      { name: 'Orange Vodka', count: 0 },
      { name: 'Triple Sec', count: 0 },
      { name: 'Pomm Liqueur', count: 0 },
      { name: 'Milagro Tequila', count: 0 },
      { name: 'Montelobos Mezcal', count: 0 },
      { name: 'Dry Vermouth', count: 0 },
      { name: 'Carpano', count: 0 },
      { name: 'Buffalo Trace', count: 0 },
      { name: 'Créme de Cassis', count: 0 },
      { name: 'Raspberry Vodka', count: 0 },
      { name: 'Raspberry Vodka', count: 0 },
      { name: 'Italicus', count: 0 },
      { name: 'Cynar', count: 0 },
      { name: 'Cointreau', count: 0 },
      { name: 'Amaro', count: 0 },
      { name: 'Aperol', count: 0 },
      { name: 'Campari', count: 0 },
      { name: '10 Mill Vodka', count: 0 },
      { name: 'Créme de Menth', count: 0 },
      { name: 'Elderflower Liqueur', count: 0 },
      { name: 'Elderflower Liqueur', count: 0 },
      { name: 'Malibu Rum', count: 0 },
      { name: 'Goslings Dark Rum', count: 0 },
      { name: 'Amaretto', count: 0 },
      { name: 'Tuaca', count: 0 },
      { name: 'Peach Schnapps', count: 0 },
      { name: 'Mt Gay Rum', count: 0 },
    ],
  },
  {
    label: '200 Speedwell',
    items: [
      { name: 'House Vodka', count: 0 },
      { name: 'House Gin', count: 0 },
      { name: 'Bacardi', count: 0 },
      { name: 'House Tequila', count: 0 },
      { name: 'House Bourbon', count: 0 },
      { name: 'House Whiskey', count: 0 },
      { name: 'Travellers Whiskey', count: 0 },
      { name: 'Casamigos Blanco', count: 0 },
      { name: 'Titos', count: 0 },
      { name: 'Grey Goose', count: 0 },
      { name: "Grey Goose L'Orange", count: 0 },
      { name: 'Ketel One', count: 0 },
      { name: 'Ketel One Citroen', count: 0 },
      { name: 'Jack Daniels', count: 0 },
      { name: 'Dewars', count: 0 },
      { name: 'Lalo Tequila', count: 0 },
      { name: 'Hendricks', count: 0 },
      { name: 'Beefeater', count: 0 },
      { name: 'Bombay Saphire', count: 0 },
      { name: 'Tanqueray', count: 0 },
      { name: 'Seagrams 7', count: 0 },
      { name: 'Captain Morgan', count: 0 },
      { name: 'Jim Beam', count: 0 },
      { name: 'Jameson', count: 0 },
      { name: 'Canadian Club', count: 0 },
      { name: 'Southern Comfort', count: 0 },
      { name: 'Bulleit Bourbon', count: 0 },
      { name: 'Bulleit Rye', count: 0 },
      { name: 'Knob Creek Bourbon', count: 0 },
      { name: 'Knob Creek Rye', count: 0 },
      { name: 'Crown Royal', count: 0 },
      { name: 'Makers Mark', count: 0 },
    ],
  },
  {
    label: '200 Top Shelf',
    items: [
      { name: 'Disaronno', count: 0 },
      { name: 'Chambord', count: 0 },
      { name: 'D.O.M Benedictine', count: 0 },
      { name: 'Grand Marnier', count: 0 },
      { name: 'St Germain', count: 0 },
      { name: 'St Germain', count: 0 },
      { name: 'B and B', count: 0 },
      { name: 'Drambuie', count: 0 },
      { name: 'Black Sambuca', count: 0 },
      { name: 'Molinari Sambuca', count: 0 },
      { name: 'Grappa', count: 0 },
      { name: 'Frangelico', count: 0 },
      { name: 'Tia Maria', count: 0 },
      { name: 'Mephisto Absinthe', count: 0 },
      { name: 'Fernet-Branca', count: 0 },
      { name: 'Hennessy V.S.O.P', count: 0 },
      { name: 'Darvelle Freres V.S.O.P', count: 0 },
      { name: 'Proper Twelve', count: 0 },
      { name: 'Whistlepig Bourbon', count: 0 },
      { name: 'Whistlepig Whiskey', count: 0 },
      { name: 'Whistlepig Whiskey', count: 0 },
      { name: 'Angels Envy', count: 0 },
      { name: 'E.H Taylor', count: 0 },
      { name: 'E.H Taylor', count: 0 },
      { name: 'Blantons', count: 0 },
      { name: 'Great Jones Bourbon', count: 0 },
      { name: 'Weller Antique 107', count: 0 },
      { name: 'Weller Special Reserve', count: 0 },
      { name: 'Buffalo Trace', count: 0 },
      { name: 'Saratoga Rye', count: 0 },
      { name: 'Calumet Farm Bourbon', count: 0 },
      { name: 'Slaughter House Whiskey', count: 0 },
      { name: 'Widow Jane', count: 0 },
      { name: 'Redeption Rye', count: 0 },
      { name: 'Redemption Bourbon', count: 0 },
      { name: 'Woodford Reserve', count: 0 },
      { name: 'Elijah Craig', count: 0 },
      { name: 'Pappy 10', count: 0 },
      { name: 'Pappy 12', count: 0 },
      { name: 'Chivas', count: 0 },
      { name: 'Balvenie 12', count: 0 },
      { name: 'Glenlivet 12', count: 0 },
      { name: 'Glenlivet 12', count: 0 },
      { name: 'Glenfiddich 12', count: 0 },
      { name: 'Glenmorangie 12', count: 0 },
      { name: 'Oban 14', count: 0 },
      { name: 'Lagavulin 16', count: 0 },
      { name: 'Talisker 10', count: 0 },
      { name: 'Talisker 10', count: 0 },
      { name: 'Johnnie Walker Black', count: 0 },
      { name: 'Johnnie Walker Red', count: 0 },
      { name: 'Johnnie Walker Gold', count: 0 },
      { name: 'Macallan 12', count: 0 },
    ]
  },
  {
    label: '400 Top Shelf',
    items: [
      { name: 'Jose Cuervo', count: 0 },
      { name: 'Clase Azul', count: 0 },
      { name: 'Riazul Plata', count: 0 },
      { name: 'Lalo', count: 0 },
      { name: 'Ocho Plata', count: 0 },
      { name: 'Ocho Reposado', count: 0 },
      { name: 'Casamigos Blanco', count: 0 },
      { name: 'Casamigos Blanco', count: 0 },
      { name: 'Casamigos Reposado', count: 0 },
      { name: 'Casamigos Añejo', count: 0 },
      { name: 'Grey Goose', count: 0 },
      { name: 'Titos', count: 0 },
      { name: 'Ketel One', count: 0 },
      { name: 'Ketel One Citroen', count: 0 },
      { name: 'Beefeater', count: 0 },
      { name: 'Tanqueray', count: 0 },
      { name: 'Hendricks', count: 0 },
      { name: 'Bombay Saphire', count: 0 },
      { name: 'Krupnik Honey Liqueur', count: 0 },
      { name: 'Chartreuse', count: 0 },
      { name: 'Barr Hill Gin', count: 0 },
      { name: 'Barr Hill Gin', count: 0 },
      { name: 'Gray Whale Gin', count: 0 },
      { name: 'Canniption Kinship Gin', count: 0 },
    ]
  },
  {
    label: 'Miscellaneous Storage',
    items: [
      { name: 'House Vodka', count: 0 },
      { name: 'House Gin', count: 0 },
      { name: 'House Rum', count: 0 },
      { name: 'House Tequila', count: 0 },
      { name: 'House Bourbon', count: 0 },
      { name: 'House Whiskey', count: 0 },
      { name: 'Triple Sec', count: 0 },
      { name: 'Créme de Cassis', count: 0 },
      { name: 'Pomm Liqueur', count: 0 },
      { name: 'Orange Vodka', count: 0 },
      { name: 'Raspberry Vodka', count: 0 },
      { name: 'Kahlua', count: 0 },
      { name: 'Bulleit Bourbon', count: 0 },
      { name: 'Bulleit Rye', count: 0 },
      { name: 'Dry Vermouth', count: 0 },
      { name: 'Carpano', count: 0 },
      { name: 'Aperol', count: 0 },
      { name: 'Campari', count: 0 },
    ]
  },
  {
    label: 'Everything Else',
    items: [
      { name: 'Apple Juice', count: 0 },
      { name: 'Pineapple Juice', count: 0 },
      { name: 'Ginger Beer', count: 0 },
      { name: 'Grapefruit Ginger Beer', count: 0 },
      { name: 'Bloodorange Puree', count: 0 },
      { name: 'Coffee', count: 0 },
      { name: 'Decaf Coffee', count: 0 },
      { name: 'Bitters', count: 0 },
      { name: 'Olives', count: 0 },
      { name: 'Cherries', count: 0 },
    ]
  }
];
